import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Providers from "./components/Provider";
import Header from "./components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="h-full overflow-hidden flex flex-col">
        <Providers>
          <Toaster position="top-center" />

          {/* HEADER (fixed height) */}
          <Header />

          {/* MAIN AREA (fills remaining space) */}
          <main className="flex-1 overflow-hidden w-7xl mx-auto">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
